version: "3.7"

services:
  redis:
    image: "redis:alpine"
    container_name: backend_cache_dev
    hostname: redis
    ports:
      - "6379:6379"

  backend_dev:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    container_name: backend_dev
    ports:
      - 8000:8000
    command: npm run dev
    environment:
      PORT: 8000
      REDIS_URL: redis://redis
