version: "3.7"

services:
  redis:
    image: "redis:alpine"
    container_name: backend_cache
    hostname: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: backend
    volumes:
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
      - 9229:9229 #debugger port
    environment:
      PORT: 8000
      REDIS_URL: redis://redis
    depends_on:
        - redis


